name: Release .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      contents: write

    strategy:
      matrix:
        rid: [linux-x64, win-x64]

    runs-on: ubuntu-latest	
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet publish ./Source --configuration Release --self-contained -r ${{ matrix.rid }} --output output/

      - name: Bump version and push tag
        uses: darioblanco/bump-semver@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive linux binary
        if: matrix.rid == 'linux-x64'
        run: zip RunCleaner_linux-x64 ./output/RunCleaner

      - name: Archive windows binary
        if: matrix.rid == 'win-x64'
        run: zip RunCleaner_win-x64 ./output/RunCleaner.exe

      - name: Publish linux release
        if: matrix.rid == 'linux-x64'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          file: ./RunCleaner_linux-x64.zip
          asset_name: RunCleaner_${{ steps.set_version.outputs.version }}_linux-x64
          release_name: ${{ steps.set_version.outputs.version }}

      - name: Publish windows release
        if: matrix.rid == 'win-x64'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          file: ./RunCleaner_win-x64.zip
          asset_name: RunCleaner_${{ steps.set_version.outputs.version }}_win-x64
          release_name: ${{ steps.set_version.outputs.version }}
